### ISSUE TITLE
(Enhancement) Claiming multiple plots at a time

### ISSUE THREAD

**Issue by FireWhisker1** [mhiaxo/ValeTowny#1]
When running the claim command I think you should be able to claim a few plots around you, like how a lot of towns have 4 plots for one large plot, so`/command 4` would claim all 4 plots making it easier for players to claim them all. You could potentially add the ability to enable and disable this in the mayor settings.

**Comment by mhiaxo** [comment]
Towny already has this with `/plot claim auto`

For the "mega plots", there's a new command in Towny that Towny mayors should use to group multiple plots into one.

```
- /plot group <add/new/create> <groupname> - Creates a plot group where a player is standing. Also adds plots to existing group.
- /plot group remove - Removes the plot you're standing in from its group.
- /plot group rename <newname> - Renames a plot group.
- /plot group set perm .... - Used to set the perm line of a group you are standing in.
- /plot group set <townblocktype> - Used to set a group of plots to a shop, farm, embassy, etc.
- /plot group toggle <fire/mobs/pvp/explosions> - Set the toggleable settings for townblocks across the entire group.
- /plot group <forsale/fs> <price> - Sets the group for sale at the set price.
- /plot group <notforsale/nfs> - Sets the group not for sale.
```
